version: "3.8"
services:
  php74_holidays:
    container_name: php74_holidays
    build:
      context: .
      dockerfile: ./.docker/PHP74_Dockerfile
    volumes:
      - .:/var/www/html
    # restart: unless-stopped
    init: true
    command: vendor/bin/phpunit tests/HolidaysTest.php

  php80_holidays:
    container_name: php80_holidays
    build:
      context: .
      dockerfile: ./.docker/PHP80_Dockerfile
    volumes:
      - .:/var/www/html
    # restart: unless-stopped
    init: true
    command: vendor/bin/phpunit tests/HolidaysTest.php
    depends_on:
      - php74_holidays

  php81_holidays:
    container_name: php81_holidays
    build:
      context: .
      dockerfile: ./.docker/PHP81_Dockerfile
    volumes:
      - .:/var/www/html
    # restart: unless-stopped
    init: true
    command: vendor/bin/phpunit tests/HolidaysTest.php
    depends_on:
      - php80_holidays

  php82_holidays:
    container_name: php82_holidays
    build:
      context: .
      dockerfile: ./.docker/PHP82_Dockerfile
    volumes:
      - .:/var/www/html
    # restart: unless-stopped
    init: true
    command: vendor/bin/phpunit tests/HolidaysTest.php
    depends_on:
      - php81_holidays
