version: "3.8"
services:
  php74:
    container_name: php74_holidays
    build:
      context: .
      dockerfile: ./.docker/PHP74_Dockerfile
    volumes:
      - .:/var/www/html
    # restart: unless-stopped
    command: vendor/bin/phpunit tests/HolidaysTest.php

  php80:
    container_name: php80_holidays
    build:
      context: .
      dockerfile: ./.docker/PHP80_Dockerfile
    volumes:
      - .:/var/www/html
    # restart: unless-stopped
    command: vendor/bin/phpunit tests/HolidaysTest.php
    depends_on:
      - php74

  php81:
    container_name: php81_holidays
    build:
      context: .
      dockerfile: ./.docker/PHP81_Dockerfile
    volumes:
      - .:/var/www/html
    # restart: unless-stopped
    command: vendor/bin/phpunit tests/HolidaysTest.php
    depends_on:
      - php80

  php82:
    container_name: php82_holidays
    build:
      context: .
      dockerfile: ./.docker/PHP82_Dockerfile
    volumes:
      - .:/var/www/html
    # restart: unless-stopped
    command: vendor/bin/phpunit tests/HolidaysTest.php
    depends_on:
      - php81
